# Generated by Django 3.2 on 2022-12-07 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20, verbose_name='Почта')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('card_number', models.IntegerField(verbose_name='Номер карточки')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=200, verbose_name='Блюдо')),
                ('start_price', models.IntegerField(verbose_name='Начальная стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование ингридиента')),
                ('extra_price', models.IntegerField(verbose_name='Надбавка')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20, verbose_name='Почта')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date_time', models.DateTimeField(auto_now_add=True)),
                ('Ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastfood.ingredient')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastfood.client')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastfood.food')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastfood.worker')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='structure',
            field=models.ManyToManyField(related_name='foods', through='fastfood.Order', to='fastfood.Ingredient'),
        ),
    ]
